### ISSUE TITLE
Basic rendering test failing

### ISSUE THREAD

**Issue by mrjjwright** [mrjjwright/nx-react#1]
@solkimicreb Not able to get tests after this [line](https://github.com/mrjjwright/nx-react/blob/master/test/componentObserve.js#L75) to work for some reason.  Perhaps you have some insight as to why the observing is failing.  It appears that for some reason `currentObserver` goes null.

**Comment by solkimicreb** [comment]
I think that the build process might mess things up. 
![image](https://cloud.githubusercontent.com/assets/6956014/22013810/33d47568-dc9b-11e6-817a-dc54f39be835.png) checking it

**Comment by mrjjwright** [comment]
Yeah I agree. It appears that multiple instances of observer function are getting loaded in webpack bundle.

On Tue, Jan 17, 2017 at 1:56 AM, Miklos Bertalan <notifications@github.com> wrote:
I think that the build process might mess things up.
[https://cloud.githubusercontent.com/assets/6956014/22013810/33d47568-dc9b-11e6-817a-dc54f39be835.png] checking it

**Comment by solkimicreb** [comment]
This might be the cause, having two instances is definitely messing things up. I am checking the webpack config

**Comment by solkimicreb** [comment]
Fixed it, it was an issue with the webpack config. NX observe has to be added as an external unless it is double bundled for the tests.

Just replace [this line](https://github.com/mrjjwright/nx-react/blob/master/webpack.config.js#L66) with this:

```js
      '@nx-js/observer-util': {
        root: 'observer',
        commonjs: '@nx-js/observer-util',
        commonjs2: '@nx-js/observer-util',
        amd: '@nx-js/observer-util'
      }
```

**Comment by mrjjwright** [comment]
That fixed it, thanks!!
